{% set name = "openff-nagl-models" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f1d71864ae9a10dae29ad3daad9f3d7a453d10daf56cdd689deb5ce9993c84b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - versioneer-518
  run:
    - python >=3.9
    - importlib_resources
  run_constrained:
    - openff-nagl >=0.3.0

test:
  imports:
    - openff.nagl_models
  requires:
    - pip

about:
  home: https://github.com/openforcefield/openff-nagl-models
  summary: 'NAGL models released by the Open Force Field Initiative'
  description: |
    This package contains NAGL models released by the Open Force Field Initiative.
    They are intended to be used by OpenFF NAGL.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/openforcefield/openff-nagl-models
  dev_url: https://github.com/openforcefield/openff-nagl-models

extra:
  recipe-maintainers:
    - lilyminium
